const SearchActionTypes = {
    SEARCH_CHANGED: 'SEARCH_CHANGED',
    TOGGLE_SEARCH: 'TOGGLE_SEARCH',
    HIDE_SEARCH: 'HIDE_SEARCH',
    SHOW_SEARCH: 'SHOW_SEARCH',
    SEARCH_SUBMITED: 'SEARCH_SUBMITED',
    TOGGLE_SUBMITED: 'TOGGLE_SUBMITED'
}

export default SearchActionTypes;