const FetchActionTypes = {
    FETCH_COMMENT_START: 'FETCH_COMMENT_START',
    FETCH_COMMENT_SUCCESS: 'FETCH_COMMENT_SUCCESS',
    FETCH_COMMENT_FAILURE: 'FETCH_COMMENT_FAILURE'
}

export default FetchActionTypes;