const DetailsActionTypes = {
    FETCH_DETAILS_START: 'FETCH_DETAILS_START',
    FETCH_DETAILS_SUCCESS: 'FETCH_DETAILS_SUCCESS',
    FETCH_DETAILS_FAILURE: 'FETCH_DETAILS_FAILURE'
}

export default DetailsActionTypes;